version: '3.8'

services:
  # The Redis Cache Server
  redis-cache:
    image: redis:latest
    container_name: product-redis-cache
    ports:
      - "6379:6379"
    restart: always

  # Bonus: A Web UI to view your Redis Cache (Optional but very helpful)
  redis-insight:
    image: redis/redisinsight:latest
    container_name: product-redis-ui
    ports:
      - "5540:5540"
    depends_on:
      - redis-cache
    restart: always

  # The RabbitMQ Message Broker (Added this section!)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-broker
    ports:
      - "5672:5672" # The standard AMQP port your code uses
      - "15672:15672" # The Web UI Management port
    environment: 
        RABBITMQ_DEFAULT_USER: guest 
        RABBITMQ_DEFAULT_PASSWORD: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

volumes:
  rabbitmq_data:
    driver: local
